---
name: Tox tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        django: [30, 31]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # TODO: pip caching

      - name: Install dependencies
        run: python -m pip install --upgrade tox

      - name: Test with tox
        env:
          TOX_ENV: ${{ format('py{0}-django{1}', matrix.python-version, matrix.django) }}
        run: tox -e $TOX_ENV